[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  JWT_SECRET = "StrongSecret!"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
