[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"

[[redirects]]
  # টোকেন ভেরিফাই করার জন্য
  from = "/verify/*"
  to = "/verify.html"
  status = 200

[[redirects]]
  # সফল ভেরিফিকেশনের পর দেখানোর জন্য
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  # 404 এররের জন্য
  from = "/*"
  to = "/404.html"
  status = 404
